apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-prometheus
  name: prometheus-lb
  namespace: monitoring
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: my-kube-prometheus-stack-prometheus
  type: LoadBalancer


