apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base    

namespace: dvss-apps-ns-vapt

namePrefix: 'vapt-'

images:
- name: xyz/details-test
  newName: apoorva6777/ll
  newTag: 0.0.1

replicas:
- name: nest-ms-deployment
  count: 1

patches:
- target:
    kind: HorizontalPodAutoscaler
    name: vapt-nest-ms-deployment-hpa
  patch: |-
    - op: replace
      path: /metadata/name
      value: nest-ms-deployment-hpa
    - op: replace
      path: /spec/minReplicas
      value: "1"

- target:
    kind: Deployment
    name: nest-ms-deployment
  patch: |-
    - op: replace
      path: /metadata/name
      value: nest-ms-deployment
    - op: replace
      path: /spec/template/metadata/labels/app
      value: nest-ms-vapt
    - op: replace
      path: /spec/selector/matchLabels/app
      value: nest-ms-vapt
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 128m
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 256Mi
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/volumes/0/csi/volumeAttributes/secretProviderClass
      value: vapt-aws-secrets

- target:
    kind: AuthorizationPolicy
    name: productpage-viewer-1
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: dvss-apps-ns-vapt
    - op: replace
      path: /spec/selector/matchLabels/app
      value: nest-ms-vapt
- target:
    kind: AuthorizationPolicy
    name: productpage-viewer
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: dvss-apps-ns-vapt
    - op: replace
      path: /spec/targetRefs/0/name
      value: vapt-nest-ms-service

- target:
    kind: ClusterRoleBinding
    name: vapt-sa-crb
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: dvss-apps-ns-vapt

- target:
    kind: Ingress
    name: nest-ms-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: onboarding.vapt.com
- target:
    kind: Service
    name: nest-ms-service
  patch: |-
    - op: replace
      path: /spec/selector/app
      value: nest-ms-vapt

- target:
    kind: SecretProviderClass
    name: aws-secrets
  patch: |-
    - op: replace
      path: /spec/parameters/objects
      value: |
        - objectName: "vapt-dvss-dc-ap1-app-secrets-ssm-param-store"
          objectType: "ssmparameter"
          jmesPath:
            - path: db_host
              objectAlias: DATABASE_HOST
            - path: db_user
              objectAlias: DATABASE_USER
            - path: db_password
              objectAlias: DATABASE_PASSWORD
            - path: redis_password
              objectAlias: REDIS_PASSWORD  
            - path: redis_host
              objectAlias: REDIS_HOST
            - path: redis_port
              objectAlias: REDIS_PORT

- target:
    kind: ServiceAccount
    name: nest-ms-service-account
  patch: |-
    - op: replace
      path: /metadata/annotations/eks.amazonaws.com~1role-arn
      value: arn:aws:iam::470954241104:role/vapt-dvss-dc-ap1-secrets-ssm-role
